config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :names
  resources :meanings
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/meaning.rb
class Meaning < ActiveRecord::Base
  belongs_to :name
  validates :meaning, presence: true
end

app/models/name.rb
class Name < ActiveRecord::Base
  has_many :meanings
  accepts_nested_attributes_for :meanings, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true, uniqueness: {case_sensitive: false}

  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  def index
    # @names = Name.all
    @q = Name.ransack(params[:q])
    @names = @q.result.page(params[:page]).per(6)
  end

  def new
    @name = Name.new
    @all_countries = Country.all
  end

  def create
    @all_countries = Country.all
    @name = Name.new(name_params)
    @name.name = params[:name][:name].capitalize
    if @name.save
      flash[:success] = 'You Name had been added'
      redirect_to name_path(@name) 
    else
      flash[:error] = "Sorry something went wrong, please try again"
      render :new
    end
  end

  def show
    @name = Name.find(params[:id])
  end

  private
  def name_params
    params.require(:name).permit(:name, :country, meanings_attributes:[:name_id, :meaning])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @q = Name.ransack(params[:q])
    @names = @q.result.page(params[:page]).per(6)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/views/layouts/_header.html.haml
%header.site_header
  .header_container
    %h1.pull-right
      = link_to root_path do
        %i.fa.fa-home 
        Whats My Name ?

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title WhatsMyName
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    / = render partial: 'layouts/header'
    = render partial: 'shared/flash_messages'
    .pic-wrapper
      %figure.pic-1
      %figure.pic-2
      %figure.pic-3
      %figure.pic-4
    %div
      .container
        = yield

app/views/names/_meaning_fields.html.haml
.nested-fields
  .col-xs-12.col-sm-10
    = f.text_area :meaning, placeholder: 'meaning', class:'form-control'
  .col-xs-4.col-sm-2
    = link_to_remove_association "X", f, class:'btn btn-danger'
  %br
  .clearfix

app/views/names/index.html.haml
.search
  = search_form_for @q, html: { class: 'search-form' } do |form|
    .col-xs-12.col-md-8.col-lg-5.m-b-1
      = form.search_field :name_cont, placeholder: 'SEARCH', class: "form-control"
    .col-xs-12.col-md-4.col-lg-3.m-b-1.text-lg-left
      = form.submit :Search, class: "btn btn-primary"
    .text-xs-center.col-xs-12.col-md-12.col-lg-4.m-b-1.text-md-center.text-lg-right
      .btn_add= link_to 'Add Your Name', new_name_path
.clearfix
%br
.alph
  - for char in 'A'..'Z'
    %a{:href => "names?utf8=✓&q%5Bname_cont%5D=#{char}"}= char
  %br
  %br
  %p Search for names by alphabet
  
-if @names.blank?
  %p There are no names containing the term(s)
  .m-y-1= link_to 'click here to add a meaning for ' "#{params[:q].values[0]}" , new_name_path
- else
  - @names.each do |n|
    %br
    - unless n.country.blank?
      .name
        .f16
          .flag{class:"#{n.country}"} &nbsp;
          %h3= link_to n.name, name_path(n)
    - else
      .name
        %h3= link_to n.name, name_path(n)
  

app/views/names/new.html.haml
= form_for @name, :url => names_path do |f|
  = render partial: 'shared/error_messages', locals: { object: @name }
  .col-xs-12.col-sm-6
    = f.text_field :name, placeholder: 'Name', class:'form-control'
  .col-xs-12.col-sm-6.m-t-1
    = f.label :country
    = f.select :country, @all_countries.collect { |c| [c.name, c.abv] }, include_blank: true, class:'form-control'
  .col-xs-12.m-t-1
    = f.fields_for :meanings do |m|
      = render 'meaning_fields', f: m
    .links.m-t-2.m-b-2
      %h1= link_to_add_association 'Add meaning', f, :meanings
  %br
  .clearfix
  .m-b-2= f.submit "Add name", class: 'btn btn-primary'

app/views/names/show.html.haml
.col-md-6.text-xs-left
  = link_to 'Add Your Name', new_name_path, class: "btn btn-success"

.col-md-6.text-xs-right
  = link_to "BACK", root_path, class: "btn btn-primary"
.name.m-t-3.p-b-3
  - unless @name.country.blank?
    .f16
      .flag{class: "#{@name.country}"} &nbsp;
      %h3= @name.name
  - else
    %h3= @name.name

  - @name.meanings.each do |m|
    %br
    %p " #{m.meaning} "

app/views/pages/index.html.haml
.search
  = search_form_for @q, html: { class: 'search-form' } do |form|
    .col-xs-12.col-md-8.col-lg-5.m-b-1
      = form.search_field :name_cont, placeholder: 'SEARCH', class: "form-control"
    .col-xs-12.col-md-4.col-lg-3.m-b-1.text-lg-left
      = form.submit :Search, class: "btn btn-primary"
    .text-xs-center.col-xs-12.col-md-12.col-lg-4.m-b-1.text-md-center.text-lg-right
      .btn_add= link_to 'Add Your Name', new_name_path
.clearfix
.alph
  - for char in 'A'..'Z'
    %a{:href => "names?utf8=✓&q%5Bname_cont%5D=#{char}"}= char
  %br
  %br
  %p Find out the meaning of your name, or add you name and its meaning to our exixting library
  

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #errorExplanation
    %h4= "Sorry the below errors occurred:"
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_flash_messages.html.haml
- unless flash.blank?
  %ul.flashes
    - flash.each do |key, value|
      %li{:class => "flash_#{key}"}= value